name: 💡 Feature Request
description: Suggest a new feature or enhancement for this library.
labels: [enhancement]
body:
  - type: textarea
    id: feature
    attributes:
      label: Feature description
      description: What feature would you like to see added?
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Why do you need this feature? What problem does it solve?
    validations:
      required: true
